baseURL = 'https://razvantudorica.net/'
locale = 'en-us'
title = 'Razvan Tudorica'
theme = "beautifulhugo"
publishDir = "docs"

[Params]
  homeTitle = "Blog"
  subtitle = ""

  mainSections = ["posts", "laws-of-software"]

[[menu.main]]
  identifier = "laws"
  name = "Laws of Software"
  url = "/laws-of-software/"
  weight = 20

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
